apiVersion: v1
kind: Service
metadata:
  name: gym-service
  labels:
    app: gym
spec:
  selector:
    app: gym
  ports:
    - protocol: TCP
      port: 5000       # The port that the service will expose on K8s Cluster
      targetPort: 5000  # ContainerPort
