apiVersion: v1
kind: Pod
metadata:
 name: gym-pod

spec:
 containers:
  - name: gym
    image: bakhtawar375/gym:latest
    env:
      - name: MYSQL_HOST
        value: "database"         # This Is Your MYSQL Service Name Or IP 
      - name: MYSQL_USER
        value: "root"
      - name: MYSQL_PASSWORD 
        value: "kali"
      - name: MYSQL_DB
        value: "gym"

    ports:
      - containerPort: 5000
    imagePullPolicy: Always 
